categories = [
    # Main categories
    BotFilterCategory(
        bot_filter_category_id=1,
        index_name="allgemeine-gesetzliche-bestimmungen",
        name_de="Allgemeine gesetzliche Bestimmungen",
        name_fr="Dispositions légales générales",
        name_it="Disposizioni legali generali",
        parent_bot_filter_category_id=None,
    ),
    BotFilterCategory(
        bot_filter_category_id=2,
        index_name="arbeitsrecht-gesamtarbeitsvertraege",
        name_de="Arbeitsrecht Gesamtarbeitsverträge",
        name_fr="Droit du travail - Conventions collectives",
        name_it="Diritto del lavoro - Contratti collettivi",
        parent_bot_filter_category_id=None,
    ),
    BotFilterCategory(
        bot_filter_category_id=3,
        index_name="baurechtliche-gesetze-verordnungen",
        name_de="Baurechtliche Gesetze und Verordnungen",
        name_fr="Lois et règlements sur la construction",
        name_it="Leggi e regolamenti edilizi",
        parent_bot_filter_category_id=None,
    ),
    BotFilterCategory(
        bot_filter_category_id=4,
        index_name="arbeitssicherheit",
        name_de="Arbeitssicherheit",
        name_fr="Sécurité au travail",
        name_it="Sicurezza sul lavoro",
        parent_bot_filter_category_id=None,
    ),
    BotFilterCategory(
        bot_filter_category_id=5,
        index_name="normen",
        name_de="Normen",
        name_fr="Normes",
        name_it="Norme",
        parent_bot_filter_category_id=None,
    ),
    # Arbeitsrecht & Gesamtarbeitsverträge subcategories
    BotFilterCategory(
        bot_filter_category_id=6,
        index_name="arbeitsrecht-gesamtarbeitsvertraege-bauhauptgewerbe",
        name_de="Bauhauptgewerbe",
        name_fr="Secteur principal de la construction",
        name_it="Settore principale della costruzione",
        parent_bot_filter_category_id=2,
    ),
    BotFilterCategory(
        bot_filter_category_id=7,
        index_name="arbeitsrecht-gesamtarbeitsvertraege-flexibler-altersruecktritt-far",
        name_de="Flexibler Altersrücktritt (FAR)",
        name_fr="Retraite anticipée flexible (FAR)",
        name_it="Pensionamento anticipato flessibile (FAR)",
        parent_bot_filter_category_id=2,
    ),
    BotFilterCategory(
        bot_filter_category_id=8,
        index_name="arbeitsrecht-gesamtarbeitsvertraege-geruestbau",
        name_de="Gerüstbau",
        name_fr="Construction d'échafaudages",
        name_it="Costruzione di ponteggi",
        parent_bot_filter_category_id=2,
    ),
    BotFilterCategory(
        bot_filter_category_id=9,
        index_name="arbeitsrecht-gesamtarbeitsvertraege-gleisbau",
        name_de="Gleisbau",
        name_fr="Construction de voies ferrées",
        name_it="Costruzione di binari",
        parent_bot_filter_category_id=2,
    ),
    # Baurechtliche Gesetze & Verordnungen - Swiss Cantons
    BotFilterCategory(
        bot_filter_category_id=10,
        index_name="baurechtliche-gesetze-verordnungen-aargau-ag",
        name_de="Aargau",
        name_fr="Argovie",
        name_it="Argovia",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=11,
        index_name="baurechtliche-gesetze-verordnungen-appenzell-ausserrhoden-ar",
        name_de="Appenzell Ausserrhoden",
        name_fr="Appenzell Rhodes-Extérieures",
        name_it="Appenzello Esterno",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=12,
        index_name="baurechtliche-gesetze-verordnungen-appenzell-innerrhoden-ai",
        name_de="Appenzell Innerrhoden",
        name_fr="Appenzell Rhodes-Intérieures",
        name_it="Appenzello Interno",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=13,
        index_name="baurechtliche-gesetze-verordnungen-basel-landschaft-bl",
        name_de="Basel-Landschaft",
        name_fr="Bâle-Campagne",
        name_it="Basilea Campagna",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=14,
        index_name="baurechtliche-gesetze-verordnungen-basel-stadt-bs",
        name_de="Basel-Stadt",
        name_fr="Bâle-Ville",
        name_it="Basilea Città",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=15,
        index_name="baurechtliche-gesetze-verordnungen-bern-be",
        name_de="Bern",
        name_fr="Berne",
        name_it="Berna",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=16,
        index_name="baurechtliche-gesetze-verordnungen-freiburg-fr",
        name_de="Freiburg",
        name_fr="Fribourg",
        name_it="Friburgo",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=17,
        index_name="baurechtliche-gesetze-verordnungen-genf-ge",
        name_de="Genf",
        name_fr="Genève",
        name_it="Ginevra",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=18,
        index_name="baurechtliche-gesetze-verordnungen-glarus-gl",
        name_de="Glarus",
        name_fr="Glaris",
        name_it="Glarona",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=19,
        index_name="baurechtliche-gesetze-verordnungen-graubuenden-gr",
        name_de="Graubünden",
        name_fr="Grisons",
        name_it="Grigioni",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=20,
        index_name="baurechtliche-gesetze-verordnungen-jura-ju",
        name_de="Jura",
        name_fr="Jura",
        name_it="Giura",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=21,
        index_name="baurechtliche-gesetze-verordnungen-luzern-lu",
        name_de="Luzern",
        name_fr="Lucerne",
        name_it="Lucerna",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=22,
        index_name="baurechtliche-gesetze-verordnungen-neuenburg-ne",
        name_de="Neuenburg",
        name_fr="Neuchâtel",
        name_it="Neuchâtel",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=23,
        index_name="baurechtliche-gesetze-verordnungen-nidwalden-nw",
        name_de="Nidwalden",
        name_fr="Nidwald",
        name_it="Nidvaldo",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=24,
        index_name="baurechtliche-gesetze-verordnungen-obwalden-ow",
        name_de="Obwalden",
        name_fr="Obwald",
        name_it="Obvaldo",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=25,
        index_name="baurechtliche-gesetze-verordnungen-schaffhausen-sh",
        name_de="Schaffhausen",
        name_fr="Schaffhouse",
        name_it="Sciaffusa",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=26,
        index_name="baurechtliche-gesetze-verordnungen-schwyz-sz",
        name_de="Schwyz",
        name_fr="Schwytz",
        name_it="Svitto",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=27,
        index_name="baurechtliche-gesetze-verordnungen-solothurn-so",
        name_de="Solothurn",
        name_fr="Soleure",
        name_it="Soletta",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=28,
        index_name="baurechtliche-gesetze-verordnungen-st-gallen-sg",
        name_de="St. Gallen",
        name_fr="Saint-Gall",
        name_it="San Gallo",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=29,
        index_name="baurechtliche-gesetze-verordnungen-tessin-ti",
        name_de="Tessin",
        name_fr="Tessin",
        name_it="Ticino",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=30,
        index_name="baurechtliche-gesetze-verordnungen-thurgau-tg",
        name_de="Thurgau",
        name_fr="Thurgovie",
        name_it="Turgovia",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=31,
        index_name="baurechtliche-gesetze-verordnungen-uri-ur",
        name_de="Uri",
        name_fr="Uri",
        name_it="Uri",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=32,
        index_name="baurechtliche-gesetze-verordnungen-waadt-vd",
        name_de="Waadt",
        name_fr="Vaud",
        name_it="Vaud",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=33,
        index_name="baurechtliche-gesetze-verordnungen-wallis-vs",
        name_de="Wallis",
        name_fr="Valais",
        name_it="Vallese",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=34,
        index_name="baurechtliche-gesetze-verordnungen-zug-zg",
        name_de="Zug",
        name_fr="Zoug",
        name_it="Zugo",
        parent_bot_filter_category_id=3,
    ),
    BotFilterCategory(
        bot_filter_category_id=35,
        index_name="baurechtliche-gesetze-verordnungen-zuerich-zh",
        name_de="Zürich",
        name_fr="Zurich",
        name_it="Zurigo",
        parent_bot_filter_category_id=3,
    ),
]
